version: '3.4'

services:
  demo.users.api:
    image: ${DOCKER_REGISTRY-}demousersapi
    build:
      context: .
      dockerfile: src/Api/Demo.Users.Api/Dockerfile

  demo.listener:
    image: ${DOCKER_REGISTRY-}demolistener
    build:
      context: .
      dockerfile: src/ConsoleApp/Demo.Listener/Dockerfile

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

